name: ball_demo
description: Example usage of Bouncy Ball.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.0.0
  ball:
    path: ../

flutter:
  uses-material-design: true
