name: ball
description: A delightfully bouncy and position-mirroring reaction to user input on a piece of Material. Totally customizable.
version: 0.1.0+1
repository: https://github.com/Zabadam/ball
issue_tracker: https://github.com/Zabadam/ball/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
